### ISSUE TITLE
表情云商店提示“页面加载失败，请检查网络后重试”，无法下载表情

### ISSUE THREAD

**Issue by shineqstm** [siyanhui/bqmm-huanxin3-demo-android#3]
吧demo运行起来后，添加了自己在表情云商店申请的bqmm.appID和 bqmm.appSecret，点击表情云商店，
表情云商店提示“页面加载失败，请检查网络后重试”，无法下载表情

**Comment by iamlixiao** [comment]
这个不太可能是代码问题所以不必在这里解决，最好QQ联系我们，我们帮你查一下ID和Secret是否有问题
